apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ui1cnkbhn-nodejs
  janus-idp.io/tekton: ui1cnkbhn-nodejs
  backstage.io/kubernetes-id: ui1cnkbhn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ui1cnkbhn-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
